eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
app:
  eureka:
    password: password
    username: eureka
spring:
  application:
    name: discovery-service
server:
  port: '8761'
